# Configure this discovery server
eureka:
  instance:
   hostname: localhost
  client: #not a client
   register-with-eureka: false
   fetch-registry: false
 
 # HTTP (Tomcat) port
server:
  port: 8080
   